FROM			alpine:3.7
MAINTAINER  	wnrhd114@gmail.com

RUN         	apk update
RUN         	apt add vim nginx supervisor 

# Pyenv
RUN				apk add --no-cache git bash build-base libffi-dev openssl-dev bzip2-dev zlib-dev readline-dev sqlite-dev 
RUN         	curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
ENV         	PATH /root/.pyenv/bin:$PATH


